### ISSUE TITLE
Fix text overflow for podcast card title and author

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#172]
e.g. http://localhost:5173/podcasts/The%20Real%20Truth%20About%20Health%20Free%2017%20Day%20Live%20Online%20Conference%20Podcast/4114648

![Image](https://github.com/user-attachments/assets/032cd706-5aff-46bd-8de5-8e3d87259c20)

# Possible Solution
- Set a `max-height` of the author and title and display scrollbars in y-axis

`PodcastCard.css`
```css
.podcast-card-title,
.podcast-card-author,
.podcast-card-title-large,
.podcast-card-author-large {
  padding: 0 !important;
  margin: 0 !important;
  /* handle text overflow, limit to max-height before scrolling in y-axis */
  overflow-y: scroll;
  max-height: 6rem;
}
```
