### ISSUE TITLE
Update podcast player style to maximize time range

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#242]
Set width of `media-time-range` to `50%`
- https://www.media-chrome.org/docs/en/styling#more-complex-component-css

```css
media-time-range {
  --media-primary-color: var(--primary-color);
  --media-preview-background: var(--primary-text-color);
  width: 50%;
}
```
